version: '3'
services:
  app:
    container_name: bigquery-runner
    build: .
    command: "tail -f /dev/null"
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - "8000:8000"
volumes:
  node-modules:
